(()=>{
const path=location.pathname;
if(path==='/index.html'||path==='/index.htm'){location.replace('/'+location.search+location.hash);return}
const body=document.body,loader=document.getElementById('site-loader'),progress=document.querySelector('.scroll-progress'),header=document.querySelector('.site-header'),menu=document.querySelector('.menu');
body.classList.remove('light');try{localStorage.removeItem('deepdell-theme')}catch(e){}document.querySelectorAll('.theme-toggle,.contact-backup').forEach(el=>el.remove());
const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content='#011434';
document.querySelectorAll('.brand').forEach(brand=>{const img=brand.querySelector('img');if(!img)return;img.src='/assets/deepdell-guideline-icon.svg';img.alt='DEEPDELL orbital mark';let word=brand.querySelector('.brand-wordmark');if(!word){word=document.createElement('span');word.className='brand-wordmark';word.textContent='DEEPDELL';brand.appendChild(word)}});
document.querySelectorAll('.footer-brand > a').forEach(brand=>{brand.innerHTML='<img class="footer-attached-logo" src="/assets/deepdell-attached-logo.webp" alt="DEEPDELL">';});
if(!document.querySelector('link[data-site-fixes]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/site-fixes.css';l.dataset.siteFixes='1';document.head.appendChild(l)}
/* Keep the Agentic Readiness Checker visible in the primary navigation on every page. */
document.querySelectorAll('.nav').forEach(nav=>{if(!nav.querySelector('a[href="agentic-check.html"]')){const a=document.createElement('a');a.href='agentic-check.html';a.textContent='Agentic Check';nav.appendChild(a)}});
/* Prefer the self-hosted icon assets. CDN icons are retained only as a compatibility fallback. */
document.querySelectorAll('img[src*="cdn.simpleicons.org/"]').forEach(img=>{const m=(img.getAttribute('src')||'').match(/cdn\.simpleicons\.org\/([^/?#]+)/);if(!m)return;const fallback=`https://cdn.jsdelivr.net/npm/simple-icons@v16/icons/${m[1]}.svg`;img.addEventListener('error',()=>{if(img.src!==fallback)img.src=fallback},{once:true});img.src=fallback});
const finish=()=>{if(!loader||loader.dataset.done)return;loader.dataset.done='1';loader.classList.add('loader-done');setTimeout(()=>loader.remove(),500)};addEventListener('load',()=>setTimeout(finish,120),{once:true});setTimeout(finish,1800);
menu?.addEventListener('click',()=>{const open=header?.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(!!open))});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>header?.classList.remove('menu-open')));
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,coarse=matchMedia('(pointer: coarse)').matches;let ticking=false;
const scroll=()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=`${max>0?Math.min(100,y/max*100):0}%`;header?.classList.toggle('scrolled',y>20);if(!reduce){document.querySelectorAll('.hero-art,.shopify-visual,.dashboard,.architecture,.contact-panel,.page-hero>div').forEach(el=>{const r=el.getBoundingClientRect(),d=(r.top+r.height/2-innerHeight/2)/innerHeight;el.style.setProperty('--scroll-tilt',`${Math.max(-5,Math.min(5,-d*7))}deg`);el.style.setProperty('--scroll-depth',`${Math.max(-32,Math.min(32,-d*24))}px`)});const a=document.querySelector('.hero-art');if(a)a.style.setProperty('--scroll-y',`${Math.max(-38,Math.min(18,y*.035))}px`)}ticking=false};addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(scroll)}},{passive:true});scroll();
const targets=document.querySelectorAll('.service,.ai-grid article,.why-grid article,.steps article,.reveal,.arch-card,.vertical,.engagement,.digital-card,.protocol,.agent-step,.ops-copy,.live-console,.page-card,.agentic-home');if('IntersectionObserver'in window&&!reduce){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});targets.forEach(el=>{el.classList.add('reveal-item');io.observe(el)})}else targets.forEach(el=>el.classList.add('visible'));
const art=document.querySelector('.hero-art');if(art&&!reduce&&!coarse){const dots=[...art.querySelectorAll('.dot')];art.addEventListener('pointerenter',()=>art.classList.add('is-hovering'));art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;art.style.setProperty('--mx',`${x*16}px`);art.style.setProperty('--my',`${y*12}px`);art.style.setProperty('--rx',`${-y*4}deg`);art.style.setProperty('--ry',`${x*5}deg`);dots.forEach((d,i)=>{const dx=((i*29)%100)/100-.5,dy=((i*47)%100)/100-.5,p=Math.max(0,1-Math.hypot(x-dx,y-dy)*2.8);d.style.transform=`translate(${(x-dx)*-18*p}px,${(y-dy)*-18*p}px) scale(${1+p*.35})`;d.style.boxShadow=p?`0 0 ${14+p*18}px rgba(32,243,251,.75)`:''})});art.addEventListener('pointerleave',()=>{art.classList.remove('is-hovering');['--mx','--my','--rx','--ry'].forEach(v=>art.style.setProperty(v,v.includes('r')?'0deg':'0px'));dots.forEach(d=>{d.style.transform='';d.style.boxShadow=''})});art.addEventListener('pointerdown',()=>{art.classList.remove('hit');void art.offsetWidth;art.classList.add('hit')})}
if(!reduce&&!coarse){document.querySelectorAll('.service,.page-card,.ai-grid article,.why-grid article,.steps article,.arch-card,.engagement,.digital-card,.protocol,.live-console,.agentic-card,.tech-item').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--card-rx',`${-y*5}deg`);card.style.setProperty('--card-ry',`${x*6}deg`);card.style.setProperty('--spot-x',`${(x+.5)*100}%`);card.style.setProperty('--spot-y',`${(y+.5)*100}%`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--card-rx','0deg');card.style.setProperty('--card-ry','0deg')})});document.querySelectorAll('.btn').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`translate(${x*3}px,${y*3}px) translateY(-2px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const intro=document.querySelector('.intro');if(intro&&!document.querySelector('.agentic-home')){const s=document.createElement('section');s.className='section-pad agentic-home';s.innerHTML=`<div class="section-kicker">02 / AGENTIC READINESS</div><div class="agentic-home-grid"><div class="agentic-home-copy"><div class="agentic-badge"><span></span>AI-READY CHECKER</div><h2>Check if your e-commerce site is <span>agentic-ready.</span></h2><p>See what autonomous shopping agents and AI systems can discover from your public website — and where the machine-readable layer needs improvement.</p><form class="agentic-mini-form" id="home-agentic-form"><input id="home-agentic-url" type="url" inputmode="url" autocomplete="url" placeholder="https://yourwebsite.com" aria-label="Website URL" required><input id="home-agentic-email" type="email" autocomplete="email" placeholder="Business email" aria-label="Business email" required><button class="btn primary" type="submit">START AUDIT <span>↗</span></button></form><p class="agentic-form-note">Your audit is public-signal based. No password, admin access or private data is requested.</p><a class="text-link" href="agentic-check.html">Open full Agentic Readiness Checker <span>↗</span></a></div><div class="agentic-preview" aria-label="Agentic checker preview"><div class="preview-window"><div class="preview-bar"><span></span><span></span><span></span><b>AGENTIC READINESS</b></div><div class="preview-body"><div class="preview-url">https://yourwebsite.com</div><div class="preview-line strong">PUBLIC DISCOVERY SCAN</div><div class="preview-checks"><i>✓</i><span>robots.txt</span><b>FOUND</b><i>✓</i><span>sitemap.xml</span><b>FOUND</b><i>✓</i><span>llms.txt</span><b>FOUND</b><i>✓</i><span>/.well-known/ucp</span><b>FOUND</b><i>✓</i><span>agent-card.json</span><b>FOUND</b><i>!</i><span>MCP endpoint</span><b class="muted">CHECK</b></div><div class="preview-score"><strong>86</strong><span>/ 100<br>READINESS</span></div></div></div></div></div><div class="agentic-how"><div><strong>01</strong><span>Enter URL</span><small>Public website address</small></div><b>→</b><div><strong>02</strong><span>Discover</span><small>Protocols & machine files</small></div><b>→</b><div><strong>03</strong><span>Report</span><small>Availability & gaps</small></div><b>→</b><div><strong>04</strong><span>Improve</span><small>DEEPDELL engineering</small></div></div>`;intro.after(s);s.querySelector('#home-agentic-form')?.addEventListener('submit',e=>{e.preventDefault();const u=s.querySelector('#home-agentic-url').value.trim(),email=s.querySelector('#home-agentic-email').value.trim();if(!u||!email)return;try{sessionStorage.setItem('deepdell-audit-email',email)}catch(err){}location.href='agentic-check.html?url='+encodeURIComponent(u)+'&email='+encodeURIComponent(email)})}
if((path==='/'||path==='')&&!document.querySelector('script[data-deepdell-schema]')){const graph={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':'https://deepdell.com/#organization','name':'DEEPDELL','url':'https://deepdell.com/','logo':'https://deepdell.com/assets/deepdell-lockup.svg','description':'Digital engineering company specialising in Shopify Plus, AI agents, agentic automation, systems integration, data and business intelligence, custom software and digital commerce.','email':'bonjour.deepdell@gmail.com','knowsAbout':['Shopify Plus','Shopify','AI agents','Agentic AI','AI automation','Digital commerce','B2B commerce','B2C commerce','Systems integration','GraphQL','React','Next.js','Node.js','TypeScript','PHP','Magento','Python','Data engineering','Business intelligence','Cloud infrastructure','Technical SEO','CRO']},{'@type':'WebSite','@id':'https://deepdell.com/#website','url':'https://deepdell.com/','name':'DEEPDELL','description':'Deep technology. Clear impact. Shopify Plus, AI, automation, data and digital engineering.','publisher':{'@id':'https://deepdell.com/#organization'}},{'@type':'WebPage','@id':'https://deepdell.com/#webpage','url':'https://deepdell.com/','name':'DEEPDELL — Shopify Plus, AI & Digital Engineering','description':'DEEPDELL engineers Shopify Plus commerce platforms, AI agents, agentic automation, business integrations, data systems and custom digital products.','isPartOf':{'@id':'https://deepdell.com/#website'},'about':{'@id':'https://deepdell.com/#organization'}}]};const sc=document.createElement('script');sc.type='application/ld+json';sc.dataset.deepdellSchema='1';sc.textContent=JSON.stringify(graph);document.head.appendChild(sc)}
const page=path.split('/').pop()||'';document.querySelectorAll('.nav a').forEach(a=>{if(a.getAttribute('href')===page)a.setAttribute('aria-current','page')});
})();

